---
title: "Tail Risk Management"
author: "Lorenzo Lucchese"
date: "07/03/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(rugarch)
library(zoo)
library(kableExtra)
library(xts)
library(cowplot)
library(grid)
library(gridExtra)
library(highfrequency)
```

## Data

Load data for empirical analysis.

```{r}
# Data 
SPY_preprocessed_data <- read_excel(
  "C:/Users/Lorenzo/Desktop/Imperial/M4/Thesis/SPY_1min_preprocessed_data.xlsx",
  col_names = FALSE, col_types = c("date", "numeric"))

corrupted_dates <- c("2019-01-09", "2020-05-26", "2020-06-04", "2020-08-05", "2020-08-10",
                     "2020-08-18", "2020-09-24", "2020-10-30")
SPY.HF <- xts(read.zoo(SPY_preprocessed_data))
# remove corrupted dates
SPY.HF <- SPY.HF[!(time(SPY.HF) %in% index(SPY.HF[corrupted_dates]))]

# daily returns
SPY.dailyreturns <- read_excel(
  "C:/Users/Lorenzo/Desktop/Imperial/M4/Thesis/SPY_daily_log_returns.xlsx",
  col_names = FALSE, col_types = c("date", "numeric"))
SPY.dailyreturns <- xts(read.zoo(SPY.dailyreturns))
# remove corrupted dates
SPY.dailyreturns <- SPY.dailyreturns[!(index(SPY.dailyreturns) %in%
                                       index(SPY.dailyreturns[corrupted_dates]))]

# discard first month of daily returns
SPY.dailyreturns <- tail(SPY.dailyreturns, -21)

```

## Selecting the cutoff threshold u

```{r}
SPY.day <- SPY.HF["2018-01-04"]
u <- u_daily(SPY.day)
SPY.day <- cbind(SPY.day, abs(SPY.day) > u)
names(SPY.day) <- c("returns", "jumps")


p_ret <- ggplot(SPY.day, aes(x = Index)) + geom_point(aes(y = returns, col = factor(jumps))) + 
  geom_hline(yintercept = u, lty = "dashed") + geom_hline(yintercept = -u, lty = "dashed") +
  ylab("HF returns") + xlab("") +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none") +
  scale_color_manual(values = c("black", "red"))
p_ret

SPY.price <- rbind(xts(c(100), order.by = as.POSIXct(c("2018-01-04 09:30:00"), tz = "UTC")),
                   100*exp(cumsum(SPY.day$returns)))
df.jumps <- data.frame(cbind(tail(index(SPY.price), -1), head(index(SPY.price), -1),
                             embed(SPY.price, 2)))
colnames(df.jumps) <- c("time.end", "time", "price.end", "price")
df.jumps$jump <- ifelse(abs(log(df.jumps$price.end) - log(df.jumps$price)) > u, 
                        "Jumps", "No jump")

p_price <- ggplot(df.jumps) + 
  geom_segment(aes(x = time, y = price, xend = time.end, yend = price.end, colour = jump)) +
  scale_x_discrete(labels = index(SPY.day)) +
  ggtitle("Identifying jumps on 2018-01-04") + ylab("price (rescaled)") +
  theme(plot.title = element_text(hjust = 0.5), legend.position = "none",
        axis.title.x = element_blank(), axis.ticks.x = element_blank(), 
        axis.text.x = element_blank()) + 
  scale_color_manual(values = c("red", "black"))
  
p_price

p <- plot_grid(p_price, p_ret, nrow = 2)

p

save_plot("Thesis plots/identifyingjumps.jpg", p, nrow = 2, dpi = 600, limitsize = FALSE)
```

## Testing the data for jumps

```{r}
# JUMP TEST

# Carry out the test on a daily basis
ep <- endpoints(SPY.HF, on = "days")
ps <- period.apply(SPY.HF, INDEX = ep, FUN = function(x) J_test(x)$p_value)
tformat(ps) <- "%Y-%m"

# plot the results of the test
p <- ggplot(ps, aes(x = Index)) + geom_point(aes(y = ps)) + ylab("p-values") +
  xlab("") + geom_hline(yintercept = 0.005, col = "red") + scale_y_continuous(trans = "log10") +
  ggtitle("Jump test p-values with 99.5% confidence level") +
  theme(plot.title = element_text(hjust = 0.5))
p

save_plot("Thesis plots/jumptest.jpg", p, dpi = 600, limitsize = FALSE)
```

## Realised Jump Tail Shape

```{r}
# compute realised jump tail shape on monthly window
suppressWarnings({RM_xi <- to_RM_xi(SPY.HF)})
```

```{r}
# Plot the realised tail jump shape (computed on rolling monthly window)
jump.xi <- RM_xi$xi_J

p <- ggplot(jump.xi, aes(x = Index)) + geom_line(aes(y = xi_J)) +
  ggtitle("S&P 500 realised jump tail shape (monthly rolling window)") +
  ylab(expression(xi[J])) + xlab("") +
  theme(plot.title = element_text(hjust = 0.5))
p

save_plot("Thesis plots/xijump.jpg", p, dpi = 600, limitsize = FALSE)
```
