---
title: "Tail Risk Management"
author: "Lorenzo Lucchese"
date: "07/03/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(rugarch)
library(zoo)
library(kableExtra)
library(xts)
library(cowplot)
library(grid)
library(gridExtra)
library(highfrequency)
```

## Data

Load data for empirical analysis.

```{r}
# Data 
SPY_preprocessed_data <- read_excel(
  "C:/Users/Lorenzo/Desktop/Imperial/M4/Thesis/SPY_1min_preprocessed_data.xlsx",
  col_names = FALSE, col_types = c("date", "numeric"))

corrupted_dates <- c("2019-01-09", "2020-05-26", "2020-06-04", "2020-08-05", "2020-08-10",
                     "2020-08-18", "2020-09-24", "2020-10-30")
SPY.HF <- xts(read.zoo(SPY_preprocessed_data))
# remove corrupted dates
SPY.HF <- SPY.HF[!(time(SPY.HF) %in% index(SPY.HF[corrupted_dates]))]

# daily returns
SPY.dailyreturns <- read_excel(
  "C:/Users/Lorenzo/Desktop/Imperial/M4/Thesis/SPY_daily_log_returns.xlsx",
  col_names = FALSE, col_types = c("date", "numeric"))
SPY.dailyreturns <- xts(read.zoo(SPY.dailyreturns))
# remove corrupted dates
SPY.dailyreturns <- SPY.dailyreturns[!(index(SPY.dailyreturns) %in%
                                       index(SPY.dailyreturns[corrupted_dates]))]

# discard first month of daily returns
SPY.dailyreturns <- tail(SPY.dailyreturns, -21)

```


## Comparing the models

We first assess the fit of the models over the whole period of data we have access to.
The HAR-EVT and R-POT model require to discard the first month of close-to-close returns and hence for consistency we do the same also for the C-EVT model.

### In-sample fit

```{r}
# Fit each model and report table with parameter estimates and confidence intervals
CEVT.fit <- CEVT_fit(SPY.dailyreturns)
suppressWarnings({HAR.EVT.fit <- HAR.EVT_fit(SPY.dailyreturns, SPY.HF)})
suppressWarnings({RPOT.fit <- RPOT_fit(SPY.dailyreturns, SPY.HF)})
```

```{r}
# retrieve parameter values
CEVT.pars <- cbind(t(data.frame(coef(CEVT.fit$GARCH.fit))), CEVT.fit$tail.pars)
rownames(CEVT.pars) <- NULL
HAR.EVT.pars <- cbind(data.frame(HAR.EVT.fit$beta.HAR), HAR.EVT.fit$tail.pars)
rownames(HAR.EVT.pars) <- NULL
RPOT.pars <- data.frame(cbind(t(RPOT.fit$pars$psi), t(RPOT.fit$pars$nu), t(RPOT.fit$pars$kappa)))
names(RPOT.pars) <- c(paste0("psi_", names(RPOT.fit$pars$psi)),
                      paste0("nu_", names(RPOT.fit$pars$nu)),
                      paste0("kappa_", names(RPOT.fit$pars$kappa)))
# compute confidence intervals for parameters
set.seed(12345)
CEVT.pars_CIs <- CEVT_bootstrapCIs(CEVT.fit)
HAR.EVT.pars_CIs <- HAR.EVT_bootstrapCIs(HAR.EVT.fit)
RPOT.pars_CIs <- RPOT_bootstrapCIs(RPOT.fit)
```

```{r}
# display results in tables
CEVT.pars_CIs_df <- cbind(CEVT.pars_CIs$GARCH.pars_CI, CEVT.pars_CIs$xi_CI,
                          CEVT.pars_CIs$beta_CI)
colnames(CEVT.pars_CIs_df) <- names(CEVT.pars[,-4])
CEVT.pars.df <- t(rbind(CEVT.pars[,-4], CEVT.pars_CIs_df))
kable(CEVT.pars.df)

HAR.EVT.pars_CIs_df <- cbind(HAR.EVT.pars_CIs$beta.HAR_CI, HAR.EVT.pars_CIs$xi_CI,
                             HAR.EVT.pars_CIs$beta_CI)
colnames(HAR.EVT.pars_CIs_df) <- names(HAR.EVT.pars[,-6])
HAR.EVT.pars.df <- t(rbind(HAR.EVT.pars[,-6], HAR.EVT.pars_CIs_df))
kable(HAR.EVT.pars.df)

RPOT.pars_CIs_df <- cbind(RPOT.pars_CIs$psi_CI, RPOT.pars_CIs$nu_CI,
                          RPOT.pars_CIs$kappa_CI)
colnames(RPOT.pars_CIs_df) <- names(RPOT.pars)
RPOT.pars.df <- t(rbind(RPOT.pars, RPOT.pars_CIs_df))
kable(RPOT.pars.df)
```

```{r}
# estimate in-sample risk measures and their CIs
set.seed(12345)
CEVT.tail <- CEVT_tails(CEVT.fit, predict = FALSE, VaR.level = 0.99)
HAR.EVT.tail <- HAR.EVT_tails(HAR.EVT.fit, predict = FALSE, VaR.level = 0.99)
RPOT.tail <- RPOT_tails(RPOT.fit, predict = FALSE, VaR.level = 0.99)
```

```{r}
# CEVT in-sample tail fit
df_plot <- data.frame(SPY.dailyreturns,
                      VaR = CEVT.tail$risk.meas$`0.99-VaR`,
                      VaR.lower = CEVT.tail$risk.meas_CI$`0.99-VaR.lower.0.95`,
                      VaR.upper = CEVT.tail$risk.meas_CI$`0.99-VaR.upper.0.95`,
                      xi = CEVT.tail$risk.meas$xi,
                      xi.lower = CEVT.tail$risk.meas_CI$xi.lower.0.95,
                      xi.upper = CEVT.tail$risk.meas_CI$xi.upper.0.95,
                      beta = CEVT.tail$risk.meas$beta,
                      beta.lower = CEVT.tail$risk.meas_CI$beta.lower.0.95,
                      beta.upper = CEVT.tail$risk.meas_CI$beta.upper.0.95)

p_VaR <- ggplot(df_plot, aes(x = index(SPY.dailyreturns))) + 
  geom_line(aes(y = x), size = 0.3, col = "skyblue4") +
  geom_line(aes(y = -VaR), size = 0.3) + 
  geom_ribbon(aes(ymin = -VaR.upper, ymax = -VaR.lower), alpha = 0.3) +
  ylab("S&P500 returns with 99% VaR") + xlab("")

p_xi <- ggplot(df_plot, aes(x = index(SPY.dailyreturns))) +
  geom_line(aes(y = xi), size = 0.3) + 
  geom_ribbon(aes(ymin = xi.lower, ymax = xi.upper), alpha = 0.3) +
  ylim(c(-1, 1)) +
  ylab(expression(paste("tail shape ", xi))) + xlab("")

p_beta <- ggplot(df_plot, aes(x = index(SPY.dailyreturns))) +
  geom_line(aes(y = beta), size = 0.3) + 
  geom_ribbon(aes(ymin = beta.lower, ymax = beta.upper), alpha = 0.3) +
  ylab(expression(paste("tail scale ", beta)))  + xlab("")


p <- plot_grid(p_VaR, p_xi, p_beta, nrow = 3)

p

save_plot("Thesis plots/CEVT_insample_tails.jpg", p, nrow = 3, dpi = 600, limitsize = FALSE)

cat("99%-VaR violations = ", sum(SPY.dailyreturns < - CEVT.tail$risk.meas$`0.99-VaR`),
    "/", length(SPY.dailyreturns))
```

```{r}
# HAR-EVT in-sample tail fit
df_plot <- data.frame(SPY.dailyreturns,
                      VaR = HAR.EVT.tail$risk.meas$`0.99-VaR`,
                      VaR.lower = HAR.EVT.tail$risk.meas_CI$`0.99-VaR.lower.0.95`,
                      VaR.upper = HAR.EVT.tail$risk.meas_CI$`0.99-VaR.upper.0.95`,
                      xi = HAR.EVT.tail$risk.meas$xi,
                      xi.lower = HAR.EVT.tail$risk.meas_CI$xi.lower.0.95,
                      xi.upper = HAR.EVT.tail$risk.meas_CI$xi.upper.0.95,
                      beta = HAR.EVT.tail$risk.meas$beta,
                      beta.lower = HAR.EVT.tail$risk.meas_CI$beta.lower.0.95,
                      beta.upper = HAR.EVT.tail$risk.meas_CI$beta.upper.0.95)

p_VaR <- ggplot(df_plot, aes(x = index(SPY.dailyreturns))) + 
  geom_line(aes(y = x), size = 0.3, col = "skyblue4") +
  geom_line(aes(y = -VaR), size = 0.3) + 
  geom_ribbon(aes(ymin = -VaR.upper, ymax = -VaR.lower), alpha = 0.3) +
  ylab("S&P500 returns with 99% VaR") + xlab("")

p_xi <- ggplot(df_plot, aes(x = index(SPY.dailyreturns))) +
  geom_line(aes(y = xi), size = 0.3) + 
  geom_ribbon(aes(ymin = xi.lower, ymax = xi.upper), alpha = 0.3) +
  ylim(c(-1, 1)) +
  ylab(expression(paste("tail shape ", xi))) + xlab("")

p_beta <- ggplot(df_plot, aes(x = index(SPY.dailyreturns))) +
  geom_line(aes(y = beta), size = 0.3) + 
  geom_ribbon(aes(ymin = beta.lower, ymax = beta.upper), alpha = 0.3) +
  ylab(expression(paste("tail scale ", beta)))  + xlab("")


p <- plot_grid(p_VaR, p_xi, p_beta, nrow = 3)

p

save_plot("HAR.EVT_insample_tails.jpg", p, nrow = 3, dpi = 600, limitsize = FALSE)

cat("99%-VaR violations = ", sum(SPY.dailyreturns < - HAR.EVT.tail$risk.meas$`0.99-VaR`),
    "/", length(SPY.dailyreturns))
```

```{r}
# RPOT in-sample tail fit
df_plot <- data.frame(SPY.dailyreturns,
                      VaR = RPOT.tail$risk.meas$`0.99-VaR`,
                      VaR.lower = RPOT.tail$risk.meas_CI$`0.99-VaR.lower.0.95`,
                      VaR.upper = RPOT.tail$risk.meas_CI$`0.99-VaR.upper.0.95`,
                      xi = RPOT.tail$risk.meas$xi,
                      xi.lower = RPOT.tail$risk.meas_CI$xi.lower.0.95,
                      xi.upper = RPOT.tail$risk.meas_CI$xi.upper.0.95,
                      beta = RPOT.tail$risk.meas$beta,
                      beta.lower = RPOT.tail$risk.meas_CI$beta.lower.0.95,
                      beta.upper = RPOT.tail$risk.meas_CI$beta.upper.0.95)

p_VaR <- ggplot(df_plot, aes(x = index(SPY.dailyreturns))) + 
  geom_line(aes(y = x), size = 0.3, col = "skyblue4") +
  geom_line(aes(y = -VaR), size = 0.3) + 
  geom_ribbon(aes(ymin = -VaR.upper, ymax = -VaR.lower), alpha = 0.3) +
  ylab("S&P500 returns with 99% VaR") + xlab("") +
  coord_cartesian(ylim = c(-0.5, 0.1))

p_xi <- ggplot(df_plot, aes(x = index(SPY.dailyreturns))) +
  geom_line(aes(y = xi), size = 0.3) + 
  geom_ribbon(aes(ymin = xi.lower, ymax = xi.upper), alpha = 0.3) +
  ylim(c(0, 0.25)) +
  ylab(expression(paste("tail shape ", xi))) + xlab("")

p_beta <- ggplot(df_plot, aes(x = index(SPY.dailyreturns))) +
  geom_line(aes(y = beta), size = 0.3) + 
  geom_ribbon(aes(ymin = beta.lower, ymax = beta.upper), alpha = 0.3) +
  ylab(expression(paste("tail scale ", beta, " (log scale)")))  + xlab("") +
  scale_y_continuous(trans = "log", labels = scales::label_number())


p <- plot_grid(p_VaR, p_xi, p_beta, nrow = 3)

p

save_plot("RPOT_insample_tails.jpg", p, nrow = 3, dpi = 600, limitsize = FALSE)

cat("99%-VaR violations = ", sum(SPY.dailyreturns < - RPOT.tail$risk.meas$`0.99-VaR`),
    "/", length(SPY.dailyreturns))
```

### Out-of-sample fit

```{r}
# pre-compute realised measures for efficiency
RM_HARJ <- to_RM_HARJ(SPY.HF)
suppressWarnings({RM_xi <- to_RM_xi(SPY.HF)})
RM_HARSJ <- to_RM_HARSJ(SPY.HF)
```

```{r}
# Plot the realised tail jump shape (computed on rolling monthly window)
jump.xi <- RM_xi$xi_J

p <- ggplot(jump.xi, aes(x = Index)) + geom_line(aes(y = xi_J)) +
  ggtitle("S&P 500 realised jump tail shape (monthly rolling window)") +
  ylab(expression(xi[J])) + xlab("") +
  theme(plot.title = element_text(hjust = 0.5))
p

save_plot("Thesis plots/xijump.jpg", p, dpi = 600, limitsize = FALSE)
```

```{r}
# parameters for out-of-sample analysis
# REM: a trading year is 252 days
window <- 400 
T. <- length(SPY.dailyreturns)
SPY.dailyreturns.test <- tail(SPY.dailyreturns, T. - window)
alpha <- 0.01
tail.forecasts_CEVT <- xts(matrix(rep(0, 3*(T. - window)), nrow = (T. - window)), 
                           order.by = index(SPY.dailyreturns.test))
tail.forecasts_HAR.EVT <- xts(matrix(rep(0, 3*(T. - window)), nrow = (T. - window)), 
                              order.by = index(SPY.dailyreturns.test))
tail.forecasts_RPOT <- xts(matrix(rep(0, 3*(T. - window)), nrow = (T. - window)), 
                           order.by = index(SPY.dailyreturns.test))
thresh_CEVT <- rep(0, T. - window)
thresh_HAR.EVT <- rep(0, T. - window)
thresh_RPOT <- rep(0, T. - window)
```
```{r}
# out of sample forecasts
for(i in 1:(T. - window)){
  # select returns and RMs
  SPY.dailyreturns_ <- SPY.dailyreturns[i:(window-1+i)]
  RM_HARJ_ <- RM_HARJ[i:(window+i),]
  RM_xi_ <- RM_xi[i:(window+i),]
  RM_HARSJ_ <- RM_HARSJ[i:(window+i),]
  # fit the models
  CEVT.fit_ <- CEVT_fit(SPY.dailyreturns_)
  HAR.EVT.fit_ <- HAR.EVT_fit(SPY.dailyreturns_, x = NULL, RM = RM_HARJ_)
  RPOT.fit_ <- RPOT_fit(SPY.dailyreturns_, x = NULL, RM_HAR = RM_HARSJ_, RM_xi = RM_xi_)
  # compute VaR_alpha, xi and beta forecasts
  CEVT.tail.forecast <- CEVT_tails(CEVT.fit_, predict = TRUE,
                                   CIs = FALSE, VaR.level = 0.99)$risk.meas
  HAR.EVT.tail.forecast <- HAR.EVT_tails(HAR.EVT.fit_, predict = TRUE, 
                                         CIs = FALSE, VaR.level = 0.99)$risk.meas
  RPOT.tail.forecast <- RPOT_tails(RPOT.fit_, predict = TRUE,
                                   CIs = FALSE, VaR.level = 0.99)$risk.meas
  # store tail risk measures (and tail threshold)
  tail.forecasts_CEVT[i,] <- as.numeric(CEVT.tail.forecast)
  tail.forecasts_HAR.EVT[i,] <- as.numeric(HAR.EVT.tail.forecast)
  tail.forecasts_RPOT[i,] <- as.numeric(RPOT.tail.forecast)
  thresh_CEVT[i] <- CEVT.fit_$u * CEVT.tail.forecast$beta/CEVT.fit_$tail.pars$beta
  thresh_HAR.EVT[i] <- HAR.EVT.fit_$u * HAR.EVT.tail.forecast$beta/HAR.EVT.fit_$tail.pars$beta
  thresh_RPOT[i] <- quantile(-RPOT.fit_$y, RPOT.fit_$thresh)
}

# re-name forecast dataframes
names(tail.forecasts_CEVT) <- names(CEVT.tail.forecast)
names(tail.forecasts_HAR.EVT) <- names(HAR.EVT.tail.forecast)
names(tail.forecasts_RPOT) <- names(RPOT.tail.forecast)
```

```{r}
# Kupiec's POF test and Christoffersen's Markov tests for VaR backtesting

# Compute p-values of test and display in table
expected_exceedances <- (T. - window) * alpha

CEVT.exceedances <- coredata(SPY.dailyreturns.test < - tail.forecasts_CEVT$`0.99-VaR`)
POF_pvalue_CEVT <- POF_test(CEVT.exceedances, alpha = alpha)
Markov_pvalue_CEVT <- Markov_test(CEVT.exceedances)

HAR.EVT.exceedances <- coredata(SPY.dailyreturns.test < -tail.forecasts_HAR.EVT$`0.99-VaR`)
POF_pvalue_HAR.EVT <- POF_test(HAR.EVT.exceedances, alpha = alpha)
Markov_pvalue_HAR.EVT <- Markov_test(HAR.EVT.exceedances)

RPOT.exceedances <- coredata(SPY.dailyreturns.test < - tail.forecasts_RPOT$`0.99-VaR`)
POF_pvalue_RPOT <- POF_test(RPOT.exceedances, alpha = alpha)
Markov_pvalue_RPOT <- Markov_test(RPOT.exceedances)

df.results <- data.frame(rep(expected_exceedances, 3), 
                         c(sum(CEVT.exceedances), sum(HAR.EVT.exceedances), sum(RPOT.exceedances)), 
                         c(POF_pvalue_CEVT, POF_pvalue_HAR.EVT, POF_pvalue_RPOT),
                         c(Markov_pvalue_CEVT, Markov_pvalue_HAR.EVT, Markov_pvalue_RPOT))
colnames(df.results) <- c("Expected Exceedances", "Actual Exceedances", "POF test (p value)", 
                          "Markov test (p value)")
kable(t(df.results), 
      col.names = c("CEVT", "HAR-EVT", "RPOT"),
      digits = 2)
```


```{r}
# out-of-sample tail fit

# qqplots of residuals against exp(1) distribution
CEVT.residuals <- exp.residuals(SPY.dailyreturns.test, tail.forecasts_CEVT, thresh_CEVT)
qqCEVT <- qplot(sample = CEVT.residuals, geom = "blank") + 
  stat_qq(distribution = qexp) + xlab("Theoretical quantiles") +
  ylab("Sample quantiles") + geom_abline(slope = 1, intercept = 0, lty = "dashed") +
  ggtitle("C-EVT residuals")

HAR.EVT.residuals <- exp.residuals(SPY.dailyreturns.test, tail.forecasts_HAR.EVT, thresh_HAR.EVT)
qqHAR.EVT <- qplot(sample = HAR.EVT.residuals, geom = "blank") +
  stat_qq(distribution = qexp) + xlab("Theoretical quantiles") +
  ylab("Sample quantiles") + geom_abline(slope = 1, intercept = 0, lty = "dashed") +
  ggtitle("HAR-EVT residuals")

RPOT.residuals <- exp.residuals(SPY.dailyreturns.test, tail.forecasts_RPOT, thresh_RPOT)
RPOT.residuals <- RPOT.residuals[-which.max(RPOT.residuals)]
qqRPOT <- qplot(sample = RPOT.residuals, geom = "blank") +
  stat_qq(distribution = qexp) + xlab("Theoretical quantiles") +
  ylab("Sample quantiles") + geom_abline(slope = 1, intercept = 0, lty = "dashed") +
  ggtitle("RPOT residuals")

p <- plot_grid(qqCEVT, qqHAR.EVT, qqRPOT, nrow = 3)

p

save_plot("Exponential_residuals.jpg", p, nrow = 3, dpi = 600, limitsize = FALSE)

# KS tests of residuals against exp(1) distribution
ks.test(CEVT.residuals, y = pexp)
ks.test(HAR.EVT.residuals, y = pexp)
ks.test(RPOT.residuals, y = pexp)
```